#pragma once
#include "GraphicsAssets.h"

enum SPRITE_INFO
{
	SPRITE_INFO_ACTIVEWATER = -5, SPRITE_INFO_TELEPORTSTAIR = -4, SPRITE_INFO_GATE1 = -3, SPRITE_INFO_STAIR = -2, SPRITE_INFO_GROUND = -1,

	SPRITE_INFO_SIMON = 0, SPRITE_INFO_ZOOMBIE = 1, SPRITE_INFO_TORCH = 2,
	SPRITE_INFO_MORNING_STAR = 3, SPRITE_INFO_EXPLOSION_EFFECT = 4, SPRITE_INFO_ITEM_MORNING_STAR = 5,
	SPRITE_INFO_ITEM_BIG_HEART = 6, SPRITE_INFO_ITEM_KNIFE = 7, SPRITE_INFO_CANDLE = 8,
	SPRITE_INFO_PANTHER = 9, SPRITE_INFO_ITEM_SMALL_HEART = 10, SPRITE_INFO_ITEM_1000PTS = 11,
	SPRITE_INFO_ITEM_700PTS = 12, SPRITE_INFO_ITEM_400PTS = 13, SPRITE_INFO_ITEM_HOLYWATER = 14,
	SPRITE_INFO_ITEM_HOLYCROSS = 15, SPRITE_INFO_GATE2 = 16, SPRITE_INFO_BRICK = 17, SPRITE_INFO_BREAKWALL1 = 18,
	SPRITE_INFO_BREAKWALL2 = 19, SPRITE_INFO_MERMAN = 20, SPRITE_INFO_MERMAN_BULLET = 21, SPRITE_INFO_BAT = 22,
	SPRITE_INFO_WATER = 23, SPRITE_INFO_KNIFE = 24, SPRITE_INFO_SCOREBAR = 25, SPRITE_INFO_VAMPIREBAT = 26,
	SPRITE_INFO_ITEM_THEAX = 27, SPRITE_INFO_ITEM_INCREASE_HEALTH = 28, SPRITE_INFO_ITEM_MAGIC_LAMP = 29, SPRITE_INFO_THEAX = 30,
	SPRITE_INFO_HOLYWATER = 31, SPRITE_INFO_ITEM_ENDGAME = 32,

	SPRITE_COUNT
};


class GraphicsAssetsManager
{
	vector<GraphicsAssets*> allGraphicsAssets;
	static GraphicsAssetsManager* instance;
public:
	static GraphicsAssetsManager* getInstance();
	static GraphicsAssets* getGraphicsAssets(int spriteInfo);
	GraphicsAssetsManager();
	~GraphicsAssetsManager();
};

